// -.-
//:() 
//thanks chat gpt for messing up what i head...
//right when i thought i could focus on the mini app game for a bit.....
//you'll never guess what ChatGPT did to me :O
    //it told me to restructure my code :D...
        //okay's no problemo i says to GPT

//a little later....guesswhat!?!?...
//The amazingly wonderful ChatGPT has a suggestion for what to do next....:))))
//LET's TRY RESTRUCTURING IT BACK THE WAY IT WAS!!!!! :) :D :O :'O ::"OO :""((((:DDDDDDDDDD
Print GN World //Idk :/\